version: "3.8"
services:
   worker:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      LOG_GROUP: $LOG_GROUP 
      SPOTIPY_CLIENT_ID: $SPOTIPY_CLIENT_ID
      SPOTIPY_CLIENT_SECRET: $SPOTIPY_CLIENT_SECRET
      OWNER_ID: $OWNER_ID
